name: publish-metrics

on:
  workflow_dispatch:

jobs:
  generate-and-publish-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Generate versioned report with charts
        run: |
          mkdir -p report
          TODAY=$(date -u +%F)
          REPORT_FILE="report/${TODAY}.html"

          echo "<html><head><title>Dev Metrics ${TODAY}</title>" > $REPORT_FILE
          echo "<script src='https://cdn.jsdelivr.net/npm/chart.js'></script>" >> $REPORT_FILE
          echo "<style>body{font-family:sans-serif;padding:2em;} h1,h2{color:#333} canvas{max-width:700px;margin-bottom:2em;}</style></head><body>" >> $REPORT_FILE
          echo "<h1>📊 Developer Metrics - ${TODAY}</h1>" >> $REPORT_FILE
          echo "<p><strong>Branch:</strong> $GITHUB_REF</p>" >> $REPORT_FILE

          echo "<h2>🔢 Total Commits:</h2><p>$(git rev-list --count HEAD)</p>" >> $REPORT_FILE

          # Top Contributors
          git shortlog -s -n | head -5 > tmp_contrib.txt
          NAMES=$(awk '{$1=""; print $0}' tmp_contrib.txt | sed 's/^ *//' | jq -R . | jq -s .)
          COUNTS=$(awk '{print $1}' tmp_contrib.txt | jq -R . | jq -s .)

          echo "<h2>👥 Top Contributors (Bar Chart):</h2><canvas id='contribChart'></canvas>" >> $REPORT_FILE
          echo "<script>
            new Chart(document.getElementById('contribChart'), {
              type: 'bar',
              data: {
