name: Bootstrap GitHub Pages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create sample index.html
        run: |
          mkdir -p report
          echo "<html><body><h1>It works!</h1><p>GitHub Pages is live.</p></body></html>" > report/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
